language: node_js
addons:
  apt:
    packages:
      - build-essentials
      - python
before_script:
  - set -eux
  - wget -O pigpio.tar http://abyz.co.uk/rpi/pigpio/pigpio.tar
  - tar -xvf pigpio.tar
  - rm pigpio.tar
  - cd PIGPIO
  - make && make install
  - npm install pigpio restify
